from os import getenv

EMAIL_LOGIN = getenv("EMAIL_LOGIN")
EMAIL_PASSWORD = getenv("EMAIL_PASSWORD")
EMAIL_PORT = getenv("EMAIL_PORT")
EMAIL_SERVER = getenv("EMAIL_SERVER")
MAILGUN_API_KEY = getenv("MAILGUN_API_KEY")
MAILGUN_DOMAIN_NAME = getenv("MAILGUN_DOMAIN_NAME")
