# docker-compose config for develop server
version: '3'
services:
  frontend:
    container_name: simba-frontend
    restart: unless-stopped
    command: yarn start
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/frontend:master-latest
    volumes:
      - ./static/:/app/static/
    depends_on:
      - backend
    expose:
      - "3015"
    ports:
      - "3015:3015"
    env_file:
      - .env
      - .env.frontend

  backend:
    container_name: simba-backend
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8010 --loop 'uvloop' --lifespan on --proxy-headers --workers 2
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/backend:master-latest
    depends_on:
      - db
      - backend-nodejs
    expose:
      - 8010
    ports:
      - 8010:8010
    env_file:
      - .env
      - .env.backend

  backend-nodejs:
    container_name: simba-backend-nodejs-local
    restart: unless-stopped
    command: yarn start
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/backend-nodejs:master-latest
    env_file:
      - .env
      - .env.backend-nodejs

  faust-worker:
    container_name: simba-faust-worker
    restart: always
    command: sh -c "sleep 40 && faust -A workers.agents worker --without-web -l info"
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/backend:master-latest
    depends_on:
      - kafka-service
    env_file:
      - .env
      - .env.backend

  faust-cron:
    container_name: simba-faust-cron
    restart: always
    command: sh -c "sleep 40 && faust -A workers.crons worker --without-web -l info"
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/backend:master-latest
    depends_on:
      - kafka-service
    env_file:
      - .env
      - .env.backend

  kafka-service:
    image: wurstmeister/kafka
    restart: always
    depends_on:
      - zookeeper
    env_file:
      - .env.kafka

  zookeeper:
    restart: always
    image: wurstmeister/zookeeper

  db:
    container_name: simba-mongodb
    restart: unless-stopped
    image: mongo:4.2-bionic
    command: mongod --port 27022 --auth
    env_file:
      - .env
      - .env.db
