# docker-compose config for develop server
version: '3'
services:
  frontend:
    container_name: simba-frontend
    restart: unless-stopped
    command: yarn start
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/frontend:master-latest
    volumes:
      - ./static/:/app/static/
    depends_on:
      - backend
    expose:
      - "3015"
    ports:
      - "3015:3015"
    env_file:
      - .env
      - .env.frontend

  backend:
    container_name: simba-backend
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8010 --loop 'uvloop' --lifespan on --proxy-headers --workers 2
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/backend:master-latest
    depends_on:
      - db
      - backend-nodejs
    expose:
      - 8010
    ports:
      - 8010:8010
    env_file:
      - .env
      - .env.backend

  backend-nodejs:
    container_name: simba-backend-nodejs-local
    restart: unless-stopped
    command: yarn start
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/backend-nodejs:master-latest
    env_file:
      - .env
      - .env.backend-nodejs

  celeryworker:
    container_name: simba-celeryworker
    restart: unless-stopped
    command: sh -c "sleep 70 && celery worker -A celery_app -P celery_pool_asyncio:TaskPool --loglevel=INFO"
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/backend:master-latest
    volumes:
      - ./backend:/backend
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env
      - .env.backend

  celerybeat:
    container_name: simba-celerybeat
    restart: unless-stopped
    command: sh -c "sleep 80 && celery beat -A celery_app --scheduler celery_pool_asyncio:PersistentScheduler --loglevel=INFO"
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/backend:master-latest
    volumes:
      - ./backend:/backend
    depends_on:
      - db
      - rabbitmq
      - celeryworker
    env_file:
      - .env
      - .env.backend

  db:
    container_name: simba-mongodb
    restart: unless-stopped
    image: mongo:4.2-bionic
    command: mongod --port 27022 --auth
    env_file:
      - .env
      - .env.db

  rabbitmq:
    container_name: simba-rabbitmq-local
    restart: unless-stopped
    image: rabbitmq:3.8.4-alpine
    env_file:
      - .env
      - .env.rabbitmq
