# docker-compose config for local development
version: '3'
services:
    frontend:
        container_name: simba-frontend-local
        command: yarn dev
        build:
            context: ./
            dockerfile: deployment/dockerfiles/Dockerfile.frontend.local
        volumes:
            - ./frontend:/frontend
        depends_on:
            - backend
        expose:
            - "3015"
        ports:
            - "3015:3015"
        env_file:
            - .env.frontend

    backend:
        container_name: simba-backend-local
        command: uvicorn main:app --host 0.0.0.0 --port 8010 --loop 'uvloop' --lifespan on --reload --proxy-headers
        build:
            context: ./
            dockerfile: deployment/dockerfiles/Dockerfile.backend.local
        volumes:
            - ./backend:/backend
        depends_on:
            - db
        expose:
            - 8010
        ports:
            - 8010:8010
        env_file:
            - .env.backend

    db:
        container_name: simba-mongodb-local
        image: mongo:4.2-bionic
        command: mongod --port 27017
        ports:
            - 27017:27017
        env_file:
            - .env.db
