# docker-compose config for develop server
version: '3'
services:
  frontend:
    container_name: simba-frontend
    restart: unless-stopped
    command: yarn start
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/frontend:develop-latest
    depends_on:
      - backend
    expose:
      - '3015'
    ports:
      - '3015:3015'
    env_file:
      - .env
      - .env.frontend

  backend:
    container_name: simba-backend
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8010 --loop 'uvloop' --lifespan on --proxy-headers
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/backend:develop-latest
    depends_on:
      - backend-nodejs
    expose:
      - 8010
    ports:
      - 8010:8010
    env_file:
      - .env
      - .env.backend

  backend-nodejs:
    container_name: simba-backend-nodejs
    restart: unless-stopped
    command: yarn start
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/backend-nodejs:develop-latest
    env_file:
      - .env
      - .env.backend-nodejs

  faust-worker:
    container_name: simba-faust-worker
    restart: always
    command: sh -c "faust -A workers.agents worker -l info"
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/backend:develop-latest
    ports:
      - 7800-7850:6066
    env_file:
      - .env
      - .env.backend

  faust-cron:
    container_name: simba-faust-cron
    restart: always
    command: sh -c "faust -A workers.crons worker -l info"
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/backend:develop-latest
    ports:
      - 6066:6066
    env_file:
      - .env
      - .env.backend
