version: '3'
services:
  workers-agent:
    command: sh -c "faust -A workers.agents worker -l info"
    build:
      context: ./
      dockerfile: deployment/dockerfiles/Dockerfile.backend.local
    volumes:
      - ./backend:/backend
      - ./.env.json:/.env.json
    env_file:
      - .env

  workers-cron:
    command: sh -c "faust -A workers.crons worker -l info"
    build:
      context: ./
      dockerfile: deployment/dockerfiles/Dockerfile.backend.local
    volumes:
      - ./backend:/backend
      - ./.env.json:/.env.json
    env_file:
      - .env
