FROM python:3.8.3-slim

ENV PYTHONUNBUFFERED=1 DOCKER=1 DEBIAN_FRONTEND=noninteractive

RUN mkdir /backend/
WORKDIR /backend/

COPY ./backend/requirements.txt /backend/
RUN pip install -r requirements.txt
