FROM node:13.8-buster

ENV DEBUG=true
ENV ENV=develop
ENV NODE_ENV=develop
ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3015
ENV API_URL=https://simba-dev.elastoo.com/api
ENV API_URL_BROWSER=https://simba-dev.elastoo.com/api
ENV SENTRY_DSN=https://99fbc649c9234967a1668a5ef519e2e2@sentry.elastoo.com/7

COPY ./frontend/ /app/
WORKDIR /app/

# Install Yarn if it is not installed
RUN yarn -v || npm install -g yarn

# Install requirements
RUN yarn install && yarn build
