FROM node:13.8-buster

ENV DEBUG=false
ENV ENV=production
ENV NODE_ENV=production
ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3015
ENV API_URL=https://my.simba.storage/api
ENV API_URL_BROWSER=https://my.simba.storage/api
ENV SENTRY_DNS=https://8636467611ef4543bb47712c35fc7980@sentry.elastoo.com/4

COPY ./frontend/ /app/
WORKDIR /app/

# Install Yarn if it is not installed
RUN yarn -v || npm install -g yarn

# Install requirements
RUN yarn install && yarn build
