FROM node:13.8-buster

ENV DEBUG=true
ENV ENV=develop
ENV NODE_ENV=develop
ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3015
ENV API_URL=https://simba-dev.elastoo.com/api
ENV API_URL_BROWSER=https://simba-dev.elastoo.com/api

RUN mkdir /frontend/
WORKDIR /frontend/

RUN yarn -v || npm install -g yarn

# Install requirements
RUN yarn install
